name: Analysis

on:
  workflow_run:
    workflows: ["Train model"]
    types:
      - completed
  workflow_dispatch:

env:
  DOLT_TOKEN: ${{ secrets.DOLT_TOKEN }}

jobs:
  check-home-access:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 1. 下载最新qlib_bin.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --repo chenditc/investment_data --pattern "qlib_bin.tar.gz"
          echo ">>> 正在解压数据..."
          mkdir -p ~/.qlib/qlib_data/cn_data
          tar -zxf qlib_bin.tar.gz -C ~/.qlib/qlib_data/cn_data --strip-components=1
          tail -n1 ~/.qlib/qlib_data/cn_data/calendars/day.txt

      - name: 2. Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "⚠️ 警告: 未找到 requirements.txt，跳过安装。"
          fi

      - name: 3. Decompress with absolute paths
        run: |
          echo ">>> 解压模型pkl..."
          cd ./roll && python ./roll.py model decompress_mlruns

      - name: 4. Verify decompressed files
        run: |
          echo ">>> 验证 ~ 目录下的内容:"
          ls -R ~/.qlibAssistant || echo "目录尚未创建"

      - name: 5. Run analysis
        env:
          MLFLOW_ALLOW_FILE_STORE: "true"
        run: |
          echo ">>> 运行分析脚本..."
          cd ./roll && python ./roll.py model selection

      - name: push qlib score to dolt
        run: |
          mkdir -p qlib_score_csv
          cp -r /home/runner/.qlibAssistant/analysis/* qlib_score_csv/
          python ./script/sync_dolt.py push_all
          rm -rf qlib_score_csv/*

      - name: 提交分析结果到 qlib_score 分支
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo ">>> 正在暂存分析结果..."
          mkdir -p /tmp/save_results
          cp -r /home/runner/.qlibAssistant/analysis/* /tmp/save_results/
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/qlib_score; then
            git checkout qlib_score
            git pull origin qlib_score
          else
            git checkout -b qlib_score
          fi
          echo ">>> 正在更新 qlib_score_csv 文件夹..."
          mkdir -p qlib_score_csv
          cp -r /tmp/save_results/* qlib_score_csv/
          git add -f qlib_score_csv/
          if git diff --cached --quiet; then
            echo "今日分析结果无变化，跳过推送。"
          else
            git commit -m "自动更新分析评分: $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin qlib_score
          fi
